# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-10 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propdata', '0002_deleted_Suburb_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='picture',
            field=models.ImageField(upload_to='houses'),
        ),
    ]
