# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propdata', '0005_added_Meta_to_Agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='message',
            new_name='address',
        ),
    ]
