# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propdata', '0007_0006_changed_housedetails_column_ownersrefnumber_and_marketheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetails',
            name='suburb',
            field=models.CharField(choices=[('Cowies Hill', 'Cowies Hill'), ('Chiltern Hills', 'Chiltern Hills'), ('Dawncliffe', 'Dawncliffe'), ('Reservoir Hills', 'Reservoir Hills'), ('Atholl Heights', 'Atholl Heights'), ('Berea West', 'Berea West'), ('Rooikoppies', 'Rooikoppies'), ('Westville', 'Westville'), ('Cato Manor', 'Cato Manor'), ('Asherville', 'Asherville'), ('Sherwood', 'Sherwood'), ('Clare Estate', 'Clare Estate')], max_length=25),
        ),
    ]
